<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>LunaCommerce | Login</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/admin_assets/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="/admin_assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/admin_assets/css/adminlte.min.css">
    <link rel="stylesheet" href="/admin_assets/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css">
    <link rel="stylesheet" href="/admin_assets/plugins/toastr/toastr.min.css">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <!-- /.login-logo -->
    <div class="card card-outline card-primary">
        <div class="card-header text-center">
            <a href="../../index2.html" class="h1"><b><?php echo Gui\Mvc\Core\Config::get('APP_NAME'); ?></a>
        </div>
        <div class="card-body">
            <p class="login-box-msg">Sign in to start your session</p>

            <form method="post">
                <div class="input-group mb-3">
                    <input type="text" id="username" class="form-control" placeholder="Username">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" id="password" class="form-control" placeholder="Password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">

                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" id="btn-logar" class="btn btn-primary btn-block">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>


            <p class="mb-1">
                <a href="forgot-password.html">I forgot my password</a>
            </p>

        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="/admin_assets/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/admin_assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="/admin_assets/js/adminlte.min.js"></script>

<script src="/admin_assets/plugins/jquery-confirm/jquery-confirm.min.js"></script>
<script src="/admin_assets/plugins/toastr/toastr.min.js"></script>


<script>

    $('#btn-logar').on('click', function (e) {
        e.preventDefault();

        if ($('#username').val() === "") {
            return toastr.error('Preencha o campo username');
        }

        if ($('#password').val() === "") {
            return toastr.error('Preencha o campo senha');
        }

        var btn = $(this);

        btn.attr('disabled', true);

        $.ajax({
            url: '/admin/auth/login',
            method: 'POST',
            data: {
                username: $('#username').val(),
                password: $('#password').val(),
            },
            success: function (res) {
                toastr.success('Redirecting ...', res.msg);
                setTimeout(() => {
                    window.location = res.redirect;
                }, 2000);
            },
            error: function (error) {
                btn.removeAttr('disabled');
                if (error) {
                    toastr.error(error.responseJSON.msg);
                }
            }
        })
    })
</script>
</body>
</html>
